name: Build Mod

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25 (for Compilation/Toolchain)
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Set up JDK 21 (for Gradle Execution)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -Porg.gradle.java.installations.paths=$JAVA_HOME_25_X64
        env:
          GRADLE_OPTS: "-Djava.version=25"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fabric-Mod-26.2
          path: build/libs/*.jar
